-- Migration 005: Extended features
--   - user_settings       (preferences, dashboard config)
--   - weekly_picks        (Sunday picks generated by scheduler)
--   - screener_history    (per-user saved screeners)

BEGIN;

-- ===== user_settings =====
CREATE TABLE IF NOT EXISTS user_settings (
    user_id              UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    notify_weekly_picks  BOOLEAN NOT NULL DEFAULT true,
    notify_market_regime BOOLEAN NOT NULL DEFAULT false,
    default_symbol       TEXT NOT NULL DEFAULT 'SPY',
    theme                TEXT NOT NULL DEFAULT 'light'
        CHECK (theme IN ('light', 'dark', 'system')),
    screener_preset      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_user_settings_updated_at ON user_settings;
CREATE TRIGGER trg_user_settings_updated_at
    BEFORE UPDATE ON user_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_settings_all ON user_settings;
CREATE POLICY user_settings_all ON user_settings
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ===== weekly_picks =====
CREATE TABLE IF NOT EXISTS weekly_picks (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL CHECK (side IN ('call', 'put', 'stock')),
    strike          NUMERIC(10, 2),
    expiry          DATE,
    entry_price     NUMERIC(10, 4) NOT NULL,
    target_price    NUMERIC(10, 4),
    stop_loss       NUMERIC(10, 4),
    rationale       TEXT NOT NULL,
    confidence      NUMERIC(3, 2) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    week_of         DATE NOT NULL,                  -- Monday of the week this pick is for
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at       TIMESTAMPTZ,
    realized_pnl    NUMERIC(12, 2),
    UNIQUE (symbol, strike, expiry, side, week_of)
);

CREATE INDEX IF NOT EXISTS idx_weekly_picks_week  ON weekly_picks(week_of DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_picks_sym   ON weekly_picks(symbol);

-- Public read (no RLS) — everyone can see picks.
ALTER TABLE weekly_picks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS weekly_picks_read ON weekly_picks;
CREATE POLICY weekly_picks_read ON weekly_picks
    FOR SELECT TO anon, authenticated USING (true);

-- No client writes; only service_role inserts/updates.

-- ===== screener_history =====
CREATE TABLE IF NOT EXISTS screener_history (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    filters      JSONB NOT NULL,
    result_count INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_screener_history_user ON screener_history(user_id, created_at DESC);

ALTER TABLE screener_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS screener_history_all ON screener_history;
CREATE POLICY screener_history_all ON screener_history
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Backfill: create default settings row when a new user is inserted.
CREATE OR REPLACE FUNCTION create_default_user_settings()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO user_settings (user_id) VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_create_settings ON users;
CREATE TRIGGER trg_users_create_settings
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION create_default_user_settings();

COMMIT;
