import { PageHeader, Card, Badge } from "../components/ui";

export function PicksPage() {
  // Weekly picks are generated by the scheduler; the API surface for this
  // is added in Phase 2.5. For now we show a placeholder card so the nav
  // route is reachable.
  const sample = [
    { symbol: "AAPL", strike: 200, expiry: "2026-07-17", side: "call", rationale: "Bullish momentum + low IV" },
    { symbol: "MSFT", strike: 410, expiry: "2026-07-17", side: "put", rationale: "Mean reversion near ATH" },
    { symbol: "SPY", strike: 555, expiry: "2026-06-20", side: "call", rationale: "Weekly trend continuation" },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Weekly Picks" subtitle="Auto-generated ideas refreshed every Sunday at 6 PM ET." />
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {sample.map((p) => (
          <Card key={`${p.symbol}-${p.strike}-${p.expiry}`} title={`${p.symbol} ${p.strike} ${p.expiry}`} subtitle={p.rationale}>
            <Badge tone={p.side === "call" ? "green" : "red"} className="uppercase">{p.side}</Badge>
          </Card>
        ))}
      </div>
    </div>
  );
}
