#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Load secrets from secrets/<env>.env and propagate to backend/.env,
# frontend/.env, and scheduler/.env.
#
# Usage:
#   ./scripts/load-secrets.sh local
#   ./scripts/load-secrets.sh production
# ----------------------------------------------------------------------------
set -euo pipefail

ENV="${1:-local}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/secrets/$ENV.env"

if [ ! -f "$SOURCE" ]; then
    echo "✗ Missing $SOURCE"
    echo "  Run: cp secrets/$ENV.env.example $SOURCE"
    echo "  Then fill in the values."
    exit 1
fi

# ---- Parse source into a tmp file we can `source` ----
TMP_ENV="$(mktemp)"
trap "rm -f $TMP_ENV" EXIT
sed 's/^[[:space:]]*#.*//' "$SOURCE" | sed '/^[[:space:]]*$/d' > "$TMP_ENV"
set -a; source "$TMP_ENV"; set +a

# Count loaded vars
COUNT=$(grep -c '=' "$SOURCE" || true)
echo "✓ Loaded $COUNT variables from $SOURCE"

stamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

# ---- Backend ----
BACKEND_ENV="$ROOT/backend/.env"
{
    echo "# Auto-generated by scripts/load-secrets.sh on $(stamp)"
    echo "# Source: secrets/$ENV.env (DO NOT EDIT — edit the source instead)"
    echo ""
    # Use `compgen -e` to list sourced env vars; filter to ALL_CAPS_WITH_UNDERSCORES
    while IFS= read -r var; do
        val=$(eval "echo \"\$$var\"")
        if [[ "$var" != VITE_* ]]; then
            echo "$var=$val"
        fi
    done < <(compgen -e | grep -E '^[A-Z][A-Z0-9_]*$' || true)
} > "$BACKEND_ENV"
echo "✓ Wrote $BACKEND_ENV"

# ---- Frontend (Vite) ----
FRONTEND_ENV="$ROOT/frontend/.env"
{
    echo "# Auto-generated by scripts/load-secrets.sh on $(stamp)"
    echo "# Source: secrets/$ENV.env"
    echo ""
    while IFS= read -r var; do
        val=$(eval "echo \"\$$var\"")
        if [[ "$var" == VITE_* ]]; then
            echo "$var=$val"
        fi
    done < <(compgen -e | grep -E '^VITE_[A-Z0-9_]*$' || true)
} > "$FRONTEND_ENV"
echo "✓ Wrote $FRONTEND_ENV"

# ---- Scheduler ----
SCHED_ENV="$ROOT/scheduler/.env"
{
    echo "# Auto-generated by scripts/load-secrets.sh on $(stamp)"
    echo "# Source: secrets/$ENV.env"
    echo ""
    for k in SUPABASE_URL SUPABASE_KEY SENDGRID_API_KEY SLACK_WEBHOOK API_URL; do
        v=$(eval "echo \"\$$k\"")
        [ -n "$v" ] && echo "$k=$v"
    done
} > "$SCHED_ENV"
echo "✓ Wrote $SCHED_ENV"

echo ""
echo "Done. You can now start the backend with: cd backend && uvicorn app.main:app --reload"
