<#
.SYNOPSIS
    Load secrets from secrets/<env>.env and propagate to backend/.env,
    frontend/.env, and scheduler/.env.

.DESCRIPTION
    Source of truth: secrets/<env>.env (git-ignored).
    Targets:
        backend/.env        - FastAPI reads this on startup
        frontend/.env       - Vite reads VITE_* vars from this
        scheduler/.env      - GitHub Actions inject these as ${{ secrets.* }}

.PARAMETER Env
    local | staging | production. Default: local

.PARAMETER Root
    Path to the repo root. Default: parent of this script's directory.

.EXAMPLE
    .\scripts\load-secrets.ps1 -Env local
    .\scripts\load-secrets.ps1 -Env production
#>

[CmdletBinding()]
param(
    [ValidateSet("local", "staging", "production")]
    [string]$Env = "local",

    [string]$Root = (Resolve-Path "$PSScriptRoot\..\").Path
)

$ErrorActionPreference = "Stop"

# ---- Resolve paths ----
$source = Join-Path $Root "secrets\$Env.env"
$backendEnv  = Join-Path $Root "backend\.env"
$frontendEnv = Join-Path $Root "frontend\.env"
$schedulerEnv = Join-Path $Root "scheduler\.env"

if (-not (Test-Path $source)) {
    Write-Host "[OK] Missing $source" -ForegroundColor Red
    Write-Host "  Run: cp secrets/$Env.env.example $source" -ForegroundColor Yellow
    Write-Host "  Then fill in the values." -ForegroundColor Yellow
    exit 1
}

# ---- Parse source ----
$vars = @{}
Get-Content $source | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#")) {
        if ($line -match '^(?<k>[A-Za-z_][A-Za-z0-9_]*)=(?<v>.*)$') {
            $vars[$matches.k] = $matches.v
        }
    }
}

Write-Host "[OK] Loaded $($vars.Count) variables from $source" -ForegroundColor Green

# ---- Compose target files ----

# Backend: every non-VITE_ var
$backendLines = @("# Auto-generated by scripts/load-secrets.ps1 on $(Get-Date -Format 'u')")
$backendLines += "# Source: secrets/$Env.env (DO NOT EDIT -- edit the source instead)"
$backendLines += ""
foreach ($k in ($vars.Keys | Sort-Object)) {
    if ($k -notmatch '^VITE_') {
        $backendLines += "$k=$($vars[$k])"
    }
}
$backendLines | Set-Content -Path $backendEnv -Encoding UTF8
Write-Host "[OK] Wrote $backendEnv" -ForegroundColor Green

# Frontend: only VITE_* (and passthrough SUPABASE_URL/ANON_KEY that Vite uses)
$frontendLines = @("# Auto-generated by scripts/load-secrets.ps1 on $(Get-Date -Format 'u')")
$frontendLines += "# Source: secrets/$Env.env (DO NOT EDIT)"
$frontendLines += ""
foreach ($k in ($vars.Keys | Sort-Object)) {
    if ($k -match '^VITE_') {
        $frontendLines += "$k=$($vars[$k])"
    }
}
$frontendLines | Set-Content -Path $frontendEnv -Encoding UTF8
Write-Host "[OK] Wrote $frontendEnv" -ForegroundColor Green

# Scheduler: minimal subset the workflows need
$schedulerKeys = @('SUPABASE_URL','SUPABASE_KEY','SENDGRID_API_KEY','SLACK_WEBHOOK','API_URL')
$schedulerLines = @("# Auto-generated by scripts/load-secrets.ps1 on $(Get-Date -Format 'u')")
$schedulerLines += "# Source: secrets/$Env.env"
$schedulerLines += ""
foreach ($k in $schedulerKeys) {
    if ($vars.ContainsKey($k)) {
        $schedulerLines += "$k=$($vars[$k])"
    }
}
$schedulerLines | Set-Content -Path $schedulerEnv -Encoding UTF8
Write-Host "[OK] Wrote $schedulerEnv" -ForegroundColor Green

Write-Host ""
Write-Host 'Done. You can now start the backend with:' -ForegroundColor Cyan
Write-Host '    cd backend ; uvicorn app.main:app --reload' -ForegroundColor Cyan
